### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by andiataleb**
Please Review this update on README

### CODE REVIEW

**Comment by jilldvn** [comment]
Review completed by LT.

**Review by ats-tandjoeng7 — COMMENTED** [review]
Approved

**Review by jilldvn — APPROVED** [review]
Review completed

**Review by jschindler11 — APPROVED** [review]
Review completed

**Review by chris820629 — APPROVED** [review]
approved!

**Review by ats-tandjoeng7 — APPROVED** [review]
Review complete

**Pull request merged**
